USE [master]
GO

/****** Object:  Database [EKZ]    Script Date: 21.12.2021 11:16:59 ******/
CREATE DATABASE [EKZ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EKZ', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\EKZ.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EKZ_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\EKZ_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EKZ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EKZ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EKZ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EKZ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EKZ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EKZ] SET ARITHABORT OFF 
GO

ALTER DATABASE [EKZ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EKZ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EKZ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EKZ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EKZ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EKZ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EKZ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EKZ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EKZ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EKZ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EKZ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EKZ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EKZ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EKZ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EKZ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EKZ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EKZ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EKZ] SET RECOVERY FULL 
GO

ALTER DATABASE [EKZ] SET  MULTI_USER 
GO

ALTER DATABASE [EKZ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EKZ] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EKZ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EKZ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EKZ] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EKZ] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EKZ] SET  READ_WRITE 
GO

